#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	"${NEXTCLOUD_PATH}"

# install app
if [ ! -e "${NEXTCLOUD_PATH}/index.php" ]; then
	tar xf /app/nextcloud.tar.bz2 -C \
		"${NEXTCLOUD_PATH}" --strip-components=1
	chown abc:abc -R \
		"${NEXTCLOUD_PATH}"
	chmod +x "${NEXTCLOUD_PATH}/occ"
fi

# run inotifyscan
s6-setuidgid abc nohup /usr/local/bin/nextcloud-inotifyscan 0<&- &>/var/log/inotify.log &
echo $! > /var/run/inotify.pid

# set cronjob
crontab /defaults/nextcloud
