#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	"${NEXTCLOUD_PATH}"

# install app
if [ ! -e "${NEXTCLOUD_PATH}/index.php" ]; then
curl -o /tmp/nextcloud.tar.bz2 -L \
	https://download.nextcloud.com/server/releases/latest.tar.bz2
tar xf /tmp/nextcloud.tar.bz2 -C \
	"${NEXTCLOUD_PATH}" --strip-components=1
rm -f \
	/tmp/nextcloud.tar.bz2
chown abc:abc -R \
	"${NEXTCLOUD_PATH}"
fi

# run inotifyscan
s6-setuidgid abc nohup /usr/local/bin/nextcloud-inotifyscan 0<&- &>/var/log/inotify.log &
echo $! > /var/run/inotify.pid

# set cronjob
crontab /defaults/nextcloud
